src/accounts/models.py
from datetime import datetime

from flask_login import UserMixin

from src import bcrypt, db


class User(UserMixin, db.Model):

    __tablename__ = "users"

    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String, unique=True, nullable=False)
    name = db.Column(db.String, nullable=False)
    password = db.Column(db.String, nullable=False)
    created_on = db.Column(db.DateTime, nullable=False)
    is_admin = db.Column(db.Boolean, nullable=False, default=False)

    def __init__(self, email, name, password, is_admin=False):
        self.email = email
        self.name = name
        self.password = bcrypt.generate_password_hash(password)
        self.created_on = datetime.now()
        self.is_admin = is_admin

    def __repr__(self):
        return f"<email {self.email}>"

src/dashboard/models.py
from datetime import datetime

from src import  db


class Tweet(db.Model):

    __tablename__ = "tweets"

    id = db.Column(db.Integer, primary_key=True)
    tweet = db.Column(db.String, unique=False, nullable=False)
    name = db.Column(db.String, nullable=False)
    username = db.Column(db.String, nullable=False)
    tweet_created_at =  db.Column(db.DateTime, nullable=False)
    sentiment = db.Column(db.String, nullable=False)
    created_on = db.Column(db.DateTime, nullable=False)

    def __init__(self, tweet, name, username, tweet_created_at, sentiment):
        self.tweet = tweet
        self.name = name
        self.username = username
        self.tweet_created_at = tweet_created_at
        self.sentiment = sentiment
        self.created_on = datetime.now()

    def __repr__(self):
        return f"<id {self.id}>"
    @property
    def formatted_created_at(self):
        return format_custom_date(self.tweet_created_at)
    
def format_custom_date(date_obj):
    day = date_obj.day
    day_suffix = "th" if 4 <= day <= 20 or 24 <= day <= 30 else ["st", "nd", "rd"][day % 10 - 1]
    
    formatted_date = date_obj.strftime(f"%d{day_suffix} %b, %Y")
    return formatted_date
    


class Feedback(db.Model):

    __tablename__ = "feedback"

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String, unique=False, nullable=False)
    phone = db.Column(db.String, unique=False, nullable=False)
    content = db.Column(db.String, nullable=False)
    created_on = db.Column(db.DateTime, nullable=False)

    def __init__(self, name, phone, content):
        self.name = name
        self.phone = phone
        self.content = content
        self.created_on = datetime.now()

    def __repr__(self):
        return f"<id {self.id}>"
    @property
    def formatted_created_on(self):
        return format_custom_date(self.created_on)

    

src/accounts/forms.py
from flask_wtf import FlaskForm
from wtforms import EmailField, PasswordField, StringField
from wtforms.validators import DataRequired, Email, EqualTo, Length

from src.accounts.models import User


class LoginForm(FlaskForm):
    email = EmailField("Email", validators=[DataRequired(), Email()])
    password = PasswordField("Password", validators=[DataRequired()])


class RegisterForm(FlaskForm):
    email = EmailField(
        "Email", validators=[DataRequired(), Email(), Length(min=6, max=40)]
    )
    name = StringField(
        "Name", validators=[DataRequired(), Length(min=3, max=40)]  # Adjust min length as needed
    )
    password = PasswordField(
        "Password", validators=[DataRequired(), Length(min=6, max=25)]
    )
    confirm = PasswordField(
        "Repeat password",
        validators=[
            DataRequired(),
            EqualTo("password", message="Passwords must match."),
        ],
    )

    def validate(self):
        initial_validation = super(RegisterForm, self).validate()
        if not initial_validation:
            return False
        user = User.query.filter_by(email=self.email.data).first()
        if user:
            self.email.errors.append("Email already registered")
            return False
        if self.password.data != self.confirm.data:
            self.password.errors.append("Passwords must match")
            return False
        return True

src/__init__.py
from decouple import config
from flask import Flask, render_template
from flask_bcrypt import Bcrypt
from flask_login import LoginManager
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy
import os
import pickle

app = Flask(__name__)
app.config.from_object(config("APP_SETTINGS"))



short_model_path = "models/logistic_regression_model.pkl"
short_vectorizer_path = "models/vectorizer.pkl"

model_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), short_model_path)
vectorizer_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), short_vectorizer_path)

dataset_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'tweets_dataset.csv')


def load_model_and_vectorizer(model_path, vectorizer_path):
    ''' 
    Parameters: model_path and vectorizer_path
    Logic: It loads and returns the model and vectorizer using the specified path
    '''

    with open(model_path, 'rb') as model_file:
        model = pickle.load(model_file)
    with open(vectorizer_path, 'rb') as vectorizer_file:
        vectorizer = pickle.load(vectorizer_file)
    return model, vectorizer

# Load our sentiment analysis model and vectorizer for later use
model, vectorizer = load_model_and_vectorizer(model_path, vectorizer_path)

def predict_text_sentiment(text = ''):
    '''
    Parameters: the text to be analyzed
    Logic: it loads the model and vectorizer and performs text sentiment analysis
    '''
    text_vec = vectorizer.transform([text])
    # Make predictions using the loaded model
    prediction = model.predict(text_vec)[0] 
    return {'sentiment': prediction}

login_manager = LoginManager()
login_manager.init_app(app)
bcrypt = Bcrypt(app)
db = SQLAlchemy(app)
migrate = Migrate(app, db)

# Registering blueprints
from src.accounts.views import accounts_bp
from src.core.views import core_bp
from src.dashboard.views import dashboards_bp

app.register_blueprint(accounts_bp)
app.register_blueprint(core_bp)
app.register_blueprint(dashboards_bp)

from src.accounts.models import User
from src.dashboard.models import Tweet
from src.dashboard.models import Feedback

login_manager.login_view = "accounts.login"
login_manager.login_message_category = "danger"


@login_manager.user_loader
def load_user(user_id):
    return User.query.filter(User.id == int(user_id)).first()


########################
#### error handlers ####
########################


@app.errorhandler(401)
def unauthorized_page(error):
    return render_template("errors/401.html"), 401


@app.errorhandler(404)
def page_not_found(error):
    return render_template("errors/404.html"), 404


@app.errorhandler(500)
def server_error_page(error):
    return render_template("errors/500.html"), 500

src/accounts/views.py
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import login_required, login_user, logout_user, current_user

from src import bcrypt, db
from src.accounts.models import User

from .forms import LoginForm, RegisterForm

accounts_bp = Blueprint("accounts", __name__)


@accounts_bp.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        flash("You are already registered.", "info")
        return redirect(url_for("core.home"))
    form = RegisterForm(request.form)
    if form.validate_on_submit():
        user = User(email=form.email.data, name=form.name.data, password=form.password.data)
        db.session.add(user)
        db.session.commit()

        login_user(user)
        flash("You registered and are now logged in. Welcome!", "success")

        return redirect(url_for("dashboards.home"))

    return render_template("accounts/register.html", form=form)


@accounts_bp.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        flash("You are already logged in.", "info")
        return redirect(url_for("core.home"))
    form = LoginForm(request.form)
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, request.form["password"]):
            login_user(user)
            # return redirect(url_for("core.home"))
            return redirect(url_for("dashboards.home"))
        else:
            flash("Invalid email and/or password.", "danger")
            return render_template("accounts/login.html", form=form)
    return render_template("accounts/login.html", form=form)


@accounts_bp.route("/logout")
@login_required
def logout():
    logout_user()
    flash("You were logged out.", "success")
    return redirect(url_for("accounts.login"))

src/core/views.py
from flask import Blueprint, render_template
from flask_login import login_required

core_bp = Blueprint("core", __name__)


@core_bp.route("/")
@login_required
def home():
    return render_template("core/index.html")

src/dashboard/views.py
from flask import Blueprint, flash, redirect, render_template, request, url_for, jsonify
from flask_login import login_required, login_user, logout_user, current_user

from src import bcrypt, db
from src.dashboard.models import Tweet, Feedback
from src import predict_text_sentiment
from src import dataset_path
import pandas as pd
import re

from datetime import datetime
import pytz

from flask_sqlalchemy import Pagination
from flask_wtf import FlaskForm
from wtforms import IntegerField

url = dataset_path

dashboards_bp = Blueprint("dashboards", __name__)

@dashboards_bp.route('/predict', methods=['GET'])
def predict_sentiment():
    try:
        text = request.args.get('text', 1, type=str)
        results = predict_text_sentiment(text)
        return jsonify({'sentiment': results['sentiment']})
    
    except Exception as e:
        return jsonify({'error': str(e)})

color_classes = ['text-success', 'text-danger', 'text-primary', 'text-info', 'text-warning']

@dashboards_bp.route("/dashboard", methods=["GET"])
@login_required
def home():
    latest_tweets = get_latest_tweets()
    tweets_and_colors = zip(latest_tweets, color_classes)
    return render_template("dashboard/pages/index.html", 
                           tweets_statistics = get_tweet_count_dictionary(),
                           tweets_and_colors = tweets_and_colors
                           )


class PaginationForm(FlaskForm):
    page = IntegerField('Page', default=1)

@dashboards_bp.route("/tweets", methods=["GET"])
@login_required
def show_tweets_page():
    page = request.args.get('page', 1, type=int)
    per_page = 20
    tweets = Tweet.query.paginate(page, per_page, False)
    pagination = Pagination(page = page, per_page = per_page, total = tweets.total, query='', items='')
    return render_template("dashboard/pages/show_tweets.html", 
                           tweets_statistics = get_tweet_count_dictionary(),
                           tweets = tweets.items, pagination = pagination, 
                           )


@dashboards_bp.route("/feedback", methods=["GET"])
@login_required
def show_feedback_page():
    page = request.args.get('page', 1, type=int)
    per_page = 20
    feedback_results = Feedback.query.paginate(page, per_page, False)
    pagination = Pagination(page = page, per_page = per_page, total = feedback_results.total, query='', items='')
    return render_template("dashboard/pages/feedback.html", 
                           feedback_results = feedback_results.items, pagination = pagination)


@dashboards_bp.route("/save-feedback", methods=["POST"])
@login_required
def save_feedback():
    name = request.form.get('name')
    phone = request.form.get('phone')
    content = request.form.get('content')

    new_feedback = Feedback(name=name, phone=phone, content=content)
    db.session.add(new_feedback)
    db.session.commit()

    flash("New feedback added.", "success")
    return redirect('/feedback')


class TweetAnalyzer:
    def __init__(self):
        # Initialize anything you need here
        pass

    def clean_tweet(self, tweet):
        '''
        Utility function to clean tweet text by removing links, special characters
        using simple regex statements.
        '''
        return ' '.join(re.sub("(@[A-Za-z0-9]+)|([^0-9A-Za-z \t])|(\w+:\/\/\S+)", " ", tweet).split())

    def get_tweet_sentiment(self, text):
        '''
        Utility function to classify sentiment of passed tweet
        using textblob's sentiment method
        '''
        #call function to predict sentiment of passed tweet
        results = predict_text_sentiment(text)
        # return results
        return results['sentiment']
    

    def get_tweets(self, count=10):
        '''
        Main function to fetch tweets and parse them.
        '''
        # Load your tweets dataset
        tweets_dataset = pd.read_csv(url)

        # Filter tweets based on query (if needed)
        filtered_tweets = tweets_dataset.head(count)

        # Initialize an empty list to store parsed tweets
        tweets = []

        # Parsing filtered tweets one by one
        #for tweet in filtered_tweets:
        for index, tweet in filtered_tweets.iterrows():
            parsed_tweet = {}
            
             # Saving text of tweet
            parsed_tweet['tweet'] = tweet['tweet']
            # Saving name of tweet owner
            parsed_tweet['name'] = tweet['name']
            # Saving username of tweet owner
            parsed_tweet['username'] = tweet['username']
             # Saving username of tweet owner
            parsed_tweet['tweet_created_at'] = tweet['created_at']
            # Saving sentiment of tweet
            parsed_tweet['sentiment'] = self.get_tweet_sentiment(tweet['tweet'])


            store_tweet(tweet = parsed_tweet['tweet'],
                        name = parsed_tweet['name'],
                        username = parsed_tweet['username'],
                        tweet_created_at = convert_utc_time_to_local_time(parsed_tweet['tweet_created_at']),
                        sentiment = parsed_tweet['sentiment'])

            # Appending parsed tweet to tweets list
            tweets.append(parsed_tweet)

        # Return parsed tweets
        return tweets

def fetch_tweets():
    api = TweetAnalyzer()
    # calling function to get tweets
    tweets = api.get_tweets(count = 10000)
    
    # picking positive tweets from tweets
    ptweets = [tweet for tweet in tweets if tweet['sentiment'] == 'positive']
    # percentage of positive tweets
    print("Positive tweets percentage: {} %".format(100*len(ptweets)/len(tweets)))
    # picking negative tweets from tweets
    ntweets = [tweet for tweet in tweets if tweet['sentiment'] == 'negative']
    # percentage of negative tweets
    print("Negative tweets percentage: {} %".format(100*len(ntweets)/len(tweets)))
    # percentage of neutral tweets
    print("Neutral tweets percentage: {} % \
            ".format(100*(len(tweets) -(len( ntweets )+len( ptweets)))/len(tweets)))
    
    return False
 

def store_tweet(tweet, name, username, tweet_created_at ,sentiment):
     new_tweet = Tweet(tweet = tweet, name = name, username = username, tweet_created_at = tweet_created_at, sentiment = sentiment)
     db.session.add(new_tweet)
     db.session.commit()

def get_tweet_count_dictionary():
    positive_tweets = Tweet.query.filter_by(sentiment='positive').count()
    negative_tweets = Tweet.query.filter_by(sentiment='negative').count()
    neutral_tweets = Tweet.query.filter_by(sentiment='neutral').count()
    all_tweets = Tweet.query.count()
    return {
    "positive_tweets": positive_tweets,
    "negative_tweets": negative_tweets,
    "neutral_tweets": neutral_tweets,
    "all_tweets": all_tweets
    }

def get_latest_tweets(count = 10):
    latest_tweets = Tweet.query.order_by(Tweet.tweet_created_at.desc()).limit(count).all()
    return latest_tweets



def convert_utc_time_to_local_time(utc_timestamp):
    # Define the UTC timestamp
    utc_timestamp = datetime.strptime("2023-02-28 00:36:05", "%Y-%m-%d %H:%M:%S")

    utc_timestamp = pytz.utc.localize(utc_timestamp)
    # Create a time zone object for Africa/Kampala
    kampala_tz = pytz.timezone('Africa/Kampala')
    # Convert the UTC timestamp to the Kampala time zone
    kampala_time = utc_timestamp.replace(tzinfo=pytz.utc).astimezone(kampala_tz)
    return kampala_time



@dashboards_bp.route("/refresh", methods=["GET"])
@login_required
def load_tweets():
    db.session.query(Tweet).delete()
    db.session.commit()
    fetch_tweets()
    flash("New tweets fetched.", "success")
    return redirect(url_for("dashboards.home"))

src/templates/dashboard/pages/feedback.html
{% extends "dashboard/_base.html" %}

{% block content %}

<div class="card">
    <div class="filter">
      <a class="icon" href="#" data-bs-toggle="dropdown"><i class="bi bi-three-dots"></i></a>
      <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow">
        <li class="dropdown-header text-start">
          <h6>Filter</h6>
        </li>

        <li><a class="dropdown-item" href="#">Today</a></li>
        <li><a class="dropdown-item" href="#">This Month</a></li>
        <li><a class="dropdown-item" href="#">This Year</a></li>
      </ul>
    </div>

    <div class="card-body">
      <h5 class="card-title">Recent Feedback <span>| Today</span></h5>
      <!-- <i class='bi bi-circle-fill activity-badge align-self-start text-success text-sm' style="font-size: .6rem; padding:0 2rem;"></i>
      Positive <i class='bi bi-circle-fill activity-badge align-self-start 
      text-info text-sm' style="font-size: .6rem; padding:0 2rem;"></i> Neutral


      <i class='bi bi-circle-fill activity-badge align-self-start text-danger text-sm' style="font-size: .6rem; padding:0 2rem;"></i> Negative
     -->
      <div class="activity">

        {% for feedback in feedback_results %}
        <div class="activity-item d-flex">
            <div class="activite-label" style="font-size: .7rem;">{{ feedback.formatted_created_on }}</div>
            <i class='bi bi-circle-fill activity-badge align-self-start text-primary'></i>
            <div class="activity-content" style="font-size: .7rem;">
                {{ feedback.content }}
            </div>
        </div>
       {% endfor %}
      </div>
      <nav aria-label="Page navigation" class="mt-4">
        <ul class="pagination" style="font-size: .6rem !important; color: black !important;">
            {% if pagination.has_prev %}
            <li class="page-item">
                <a class="page-link" href="?page={{ pagination.prev_num }}">Previous</a>
            </li>
            {% endif %}

            {% for num in pagination.iter_pages() %}
            <li class="page-item {% if num == pagination.page %}active{% endif %}">
                <a class="page-link" href="?page={{ num }}">{{ num }}</a>
            </li>
            {% endfor %}

            {% if pagination.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ pagination.next_num }}">Next</a>
            </li>
            {% endif %}
        </ul>
    </nav>
    </div>

   
  </div><!-- End Recent Activity -->

  <script src="https://cdn.quilljs.com/1.3.6/quill.js"></script>
  <div class="section">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                  <h5 class="card-title">Give us feedback</h5>
    
                  <!-- Floating Labels Form -->
                  <form class="row g-3"  action="{{ url_for('dashboards.save_feedback') }}" method="POST">
                    <div class="col-md-6">
                      <div class="form-floating">
                        <input type="text" name="name" class="form-control" id="floatingName" placeholder="Your Name" required>
                        <label for="floatingName">Your Name</label>
                      </div>
                    </div>
                    <div class="col-md-6">
                      <div class="form-floating">
                        <input type="contact" class="form-control" name="phone" id="floatingContact" placeholder="Contact" required>
                        <label for="floatingContact">Contact</label>
                      </div>
                    </div>
                    <div class="col-12">
                      <div class="form-floating">
                        <textarea class="form-control" name="content" placeholder="Feedback" id="floatingTextarea" style="height: 100px;" required></textarea>
                        <label for="floatingTextarea">Feedback</label>
                      </div>
                    </div>
               
                    <div class="text-center">
                      <button type="submit" class="btn btn-primary">Submit</button>
                      <button type="reset" class="btn btn-secondary">Reset</button>
                    </div>
                  </form>
                  
                  <!-- End floating Labels Form -->
    
                </div>
              </div>

        </div>
    </div>
</div>




{% endblock %}

src/templates/dashboard/pages/show_tweets.html
{% extends "dashboard/_base.html" %}

{% block content %}

<div class="card">
    <div class="filter">
      <a class="icon" href="#" data-bs-toggle="dropdown"><i class="bi bi-three-dots"></i></a>
      <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow">
        <li class="dropdown-header text-start">
          <h6>Filter</h6>
        </li>

        <li><a class="dropdown-item" href="#">Today</a></li>
        <li><a class="dropdown-item" href="#">This Month</a></li>
        <li><a class="dropdown-item" href="#">This Year</a></li>
      </ul>
    </div>

    <div class="card-body">
      <h5 class="card-title">Recent Tweets <span>| Today</span></h5>
      <i class='bi bi-circle-fill activity-badge align-self-start text-success text-sm' style="font-size: .6rem; padding:0 2rem;"></i>
      Positive <i class='bi bi-circle-fill activity-badge align-self-start 
      text-info text-sm' style="font-size: .6rem; padding:0 2rem;"></i> Neutral


      <i class='bi bi-circle-fill activity-badge align-self-start text-danger text-sm' style="font-size: .6rem; padding:0 2rem;"></i> Negative
    
      <br> <br>
      <div class="activity">

        {% for tweet in tweets %}
        <div class="activity-item d-flex">
            <div class="activite-label" style="font-size: .7rem;">{{ tweet.formatted_created_at }}</div>
            <i class='bi bi-circle-fill activity-badge align-self-start {% if tweet.sentiment == "positive" %}text-success{% endif %}{% if tweet.sentiment == "neutral" %}text-info{% endif %} {% if tweet.sentiment == "negative" %}text-danger{% endif %}'></i>
            <div class="activity-content" style="font-size: .7rem;">
                {{ tweet.tweet }}
            </div>
        </div>
       {% endfor %}
      </div>

      <nav aria-label="Page navigation" class="mt-4">
        <ul class="pagination" style="font-size: .6rem !important; color: black !important;">
            {% if pagination.has_prev %}
            <li class="page-item">
                <a class="page-link" href="?page={{ pagination.prev_num }}">Previous</a>
            </li>
            {% endif %}

            {% for num in pagination.iter_pages() %}
            <li class="page-item {% if num == pagination.page %}active{% endif %}">
                <a class="page-link" href="?page={{ num }}">{{ num }}</a>
            </li>
            {% endfor %}

            {% if pagination.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ pagination.next_num }}">Next</a>
            </li>
            {% endif %}
        </ul>
    </nav>



    </div>
  </div><!-- End Recent Activity -->


{% endblock %}